services:
  worker-processing:
    container_name: airbim-worker-processing-gpu
    image: airbim-worker-processing:gpu
    build:
      args:
        EXTRAS: "[gpu]"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
