services:
  storage:
    container_name: airbim-storage
    image: quay.io/minio/minio:latest
    restart: unless-stopped
    environment:
      - MINIO_ROOT_USER=${STORAGE_ACCESS_KEY_ID}
      - MINIO_ROOT_PASSWORD=${STORAGE_SECRET_KEY}
      - MINIO_BUCKET=${STORAGE_BUCKET}
    command: server /data --console-address ":9001"
    ports:
      - "${STORAGE_PORT_EXTERNAL}:${STORAGE_PORT_INTERNAL}"
      - "9001:9001"
    volumes:
      - storage_data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "${STORAGE_INTERNAL_ENDPOINT}/minio/health/live" ]
      interval: 1s
      timeout: 5s
      retries: 5

  database:
    container_name: airbim-database
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${DB_PORT_EXTERNAL:-5432}:${DB_PORT_INTERNAL:-5432}"
    volumes:
      - database_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 1s
      timeout: 5s
      retries: 5
    depends_on:
      storage:
        condition: service_healthy

  cache:
    container_name: airbim-cache
    image: redis:latest
    restart: unless-stopped
    command: [ "redis-server", "--requirepass", "${CACHE_PASSWORD}", "--appendonly", "yes" ]
    ports:
      - "${CACHE_PORT_EXTERNAL:-6379}:${CACHE_PORT_INTERNAL:-6379}"
    volumes:
      - cache_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "$CACHE_PASSWORD", "ping" ]
      interval: 1s
      timeout: 5s
      retries: 5
    depends_on:
      database:
        condition: service_healthy

  broker:
    container_name: airbim-broker
    image: redis:latest
    restart: unless-stopped
    command: [ "redis-server", "--port", "6380", "--requirepass", "${BROKER_PASSWORD}", "--appendonly", "yes" ]
    ports:
      - "${BROKER_PORT_EXTERNAL:-6380}:${BROKER_PORT_EXTERNAL:-6380}"
    volumes:
      - broker_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "${BROKER_PORT_EXTERNAL:-6380}", "-a", "$BROKER_PASSWORD", "ping" ]
      interval: 1s
      timeout: 5s
      retries: 5
    depends_on:
      cache:
        condition: service_healthy

  worker:
    container_name: airbim-worker
    command: [ "celery", "-A", "infrastructure.celery_app:celery_app", "worker", "-l", "info", "-Q", "default", "--concurrency=4" ]
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "celery inspect ping --destination celery@$$HOSTNAME" ]
      interval: 1s
      timeout: 5s
      retries: 5
    depends_on:
      broker:
        condition: service_healthy
      database:
        condition: service_healthy

  worker-converter:
    container_name: airbim-worker-converter
    command: [ "celery", "-A", "infrastructure.celery_app:celery_app", "worker", "-l", "info", "-Q", "converter", "--concurrency=8" ]
    build:
      context: ./backend
      dockerfile: Dockerfile.converter
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "celery inspect ping --destination celery@$$HOSTNAME" ]
      interval: 1s
      timeout: 5s
      retries: 5
    depends_on:
      worker:
        condition: service_healthy

  worker-processing:
    container_name: airbim-worker-processing
    command: [ "micromamba", "run", "-n", "base", "python", "-m", "celery", "-A", "infrastructure.celery_app:celery_app", "worker", "-l", "info", "-Q", "processing", "--concurrency=8" ]
    build:
      context: ./backend
      dockerfile: Dockerfile.processing
      args:
        EXTRAS: ""
      secrets:
        - github_token
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "micromamba run -n base python -m celery inspect ping --destination celery@$$HOSTNAME" ]
      interval: 1s
      timeout: 5s
      retries: 5
    depends_on:
      worker-converter:
        condition: service_healthy

  beat:
    container_name: airbim-beat
    command: [ "celery", "-A", "infrastructure.celery_app:celery_app", "beat", "-l", "info" ]
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "${BROKER_PORT_EXTERNAL:-6380}", "-a", "$BROKER_PASSWORD", "ping" ]
      interval: 1s
      timeout: 5s
      retries: 5
    depends_on:
      worker-processing:
        condition: service_healthy

  flower:
    container_name: airbim-flower
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: [ "celery", "-A", "infrastructure.celery_app:celery_app", "flower" ]
    env_file:
      - .env
    ports:
      - "${FLOWER_PORT:-5555}:5555"
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "${BROKER_PORT_EXTERNAL:-6380}", "-a", "$BROKER_PASSWORD", "ping" ]
      interval: 1s
      timeout: 5s
      retries: 5
    depends_on:
      worker-processing:
        condition: service_healthy

  backend:
    container_name: airbim-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      API_HOST: 0.0.0.0
      API_PORT: 8000
      DB_HOST: database
      DB_PORT: 5432
    ports:
      - "${API_PORT:-8000}:8000"
    depends_on:
      worker-processing:
        condition: service_healthy

volumes:
  database_data:
  storage_data:
  cache_data:
  broker_data:

secrets:
  github_token:
    file: ./.github_token
