# syntax=docker/dockerfile:1
FROM mambaorg/micromamba:latest

ENV MAMBA_DOCKERFILE_ACTIVATE=1

USER root
WORKDIR /app

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update \
    && apt-get install -y --no-install-recommends \
    git \
    fonts-dejavu-core \
    libxcursor1 \
    libx11-6 \
    libgl1 \
    libglib2.0-0 \
    xvfb

USER $MAMBA_USER

RUN micromamba install -y -n base -c conda-forge \
    python=3.12 \
    pip "python-pdal>=3.5" \
    && micromamba clean --all --yes

ARG EXTRAS=""
ENV EXTRAS=${EXTRAS}

COPY --chown=$MAMBA_USER:$MAMBA_USER requirements.base.txt requirements.worker.txt requirements.processing.txt /tmp/requirements/

RUN sed 's/\${EXTRAS}/'"$EXTRAS"'/g' /tmp/requirements/requirements.processing.txt > /tmp/requirements/requirements.patched.txt

RUN --mount=type=cache,target=/opt/pip-cache,uid=57439 \
    --mount=type=secret,id=github_token,uid=57439 \
    export GITHUB_TOKEN=$(cat /run/secrets/github_token) && \
    PIP_CACHE_DIR=/opt/pip-cache micromamba run -n base pip install -r /tmp/requirements/requirements.patched.txt

COPY --chown=$MAMBA_USER:$MAMBA_USER . .
