# syntax=docker/dockerfile:1
FROM python:3.13-slim

WORKDIR /app

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update \
    && apt-get install -y --no-install-recommends \
    fonts-dejavu-core

COPY requirements.base.txt requirements.worker.txt ./
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install -r requirements.worker.txt

COPY . .
