# Generated by Django 2.2.27 on 2025-10-15 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0044_task_console_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='BIMFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('LAZ', 'Point Cloud (LAZ)'), ('LAS', 'Point Cloud (LAS)'), ('GEOTIFF', 'GeoTIFF Raster')], help_text='Type of the file', max_length=10, verbose_name='File Type')),
                ('original_filename', models.CharField(help_text='Original filename', max_length=255, verbose_name='Original Filename')),
                ('file_path', models.CharField(help_text='Relative path to the file from MEDIA_ROOT', max_length=512, verbose_name='File Path')),
                ('size', models.BigIntegerField(help_text='File size in bytes', verbose_name='Size')),
                ('user', models.ForeignKey(help_text='User who uploaded this file', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'BIM File',
                'verbose_name_plural': 'BIM Files',
            },
        ),
    ]
