"""update task model

Revision ID: 02157d6e26bf
Revises: f30fb4fed8db
Create Date: 2026-06-01 20:36:55.532571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02157d6e26bf'
down_revision: Union[str, Sequence[str], None] = 'f30fb4fed8db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recording_results', 'point_cloud_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recording_results', 'point_cloud_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
