"""fix error with Invitation ref

Revision ID: 04f7d31193e8
Revises: f8b09436fd17
Create Date: 2026-03-12 12:39:39.345950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04f7d31193e8'
down_revision: Union[str, Sequence[str], None] = 'f8b09436fd17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invite_links', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('invite_links_inviter_id_fkey'), 'invite_links', type_='foreignkey')
    op.create_foreign_key(None, 'invite_links', 'users', ['creator_id'], ['id'], ondelete='CASCADE')
    op.drop_column('invite_links', 'inviter_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invite_links', sa.Column('inviter_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'invite_links', type_='foreignkey')
    op.create_foreign_key(op.f('invite_links_inviter_id_fkey'), 'invite_links', 'users', ['inviter_id'], ['id'], ondelete='CASCADE')
    op.drop_column('invite_links', 'creator_id')
    # ### end Alembic commands ###
