"""add workspace id to files

Revision ID: 10d5e1a82494
Revises: 6ba7ac92ebe1
Create Date: 2026-05-20 06:11:48.446487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10d5e1a82494'
down_revision: Union[str, Sequence[str], None] = '6ba7ac92ebe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('workspace_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'files', 'workspaces', ['workspace_id'], ['id'])
    op.create_unique_constraint(None, 'point_cloud_converted', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'point_cloud_converted', type_='unique')
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_column('files', 'workspace_id')
    # ### end Alembic commands ###
