"""update stage model

Revision ID: 2b4e502611f2
Revises: 995848684be6
Create Date: 2026-06-05 07:25:37.701953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b4e502611f2'
down_revision: Union[str, Sequence[str], None] = '995848684be6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('files_workspace_id_fkey'), 'files', type_='foreignkey')
    op.create_foreign_key(None, 'files', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('stages', sa.Column('name', sa.String(), nullable=True))
    op.add_column('stages', sa.Column('description', sa.String(), nullable=True))
    op.add_column('stages', sa.Column('start_date', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stages', 'start_date')
    op.drop_column('stages', 'description')
    op.drop_column('stages', 'name')
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.create_foreign_key(op.f('files_workspace_id_fkey'), 'files', 'workspaces', ['workspace_id'], ['id'])
    # ### end Alembic commands ###
