"""refactor file models

Revision ID: 450ff7e83000
Revises: 8d9dd44bed99
Create Date: 2026-03-26 14:55:06.692660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '450ff7e83000'
down_revision: Union[str, Sequence[str], None] = '8d9dd44bed99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('extension', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PENDING', name='file_statuses', create_constraint=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.add_column('bim_files', sa.Column('file_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'bim_files', ['file_id'])
    op.create_foreign_key(None, 'bim_files', 'files', ['file_id'], ['id'])
    op.drop_column('bim_files', 'extension')
    op.drop_column('bim_files', 'size')
    op.drop_column('bim_files', 'path')
    op.add_column('point_cloud_files', sa.Column('file_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'point_cloud_files', ['file_id'])
    op.create_foreign_key(None, 'point_cloud_files', 'files', ['file_id'], ['id'])
    op.drop_column('point_cloud_files', 'extension')
    op.drop_column('point_cloud_files', 'size')
    op.drop_column('point_cloud_files', 'path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('point_cloud_files', sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('point_cloud_files', sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('point_cloud_files', sa.Column('extension', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'point_cloud_files', type_='foreignkey')
    op.drop_constraint(None, 'point_cloud_files', type_='unique')
    op.drop_column('point_cloud_files', 'file_id')
    op.add_column('bim_files', sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('bim_files', sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('bim_files', sa.Column('extension', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bim_files', type_='foreignkey')
    op.drop_constraint(None, 'bim_files', type_='unique')
    op.drop_column('bim_files', 'file_id')
    op.drop_table('files')
    # ### end Alembic commands ###
