"""added point clouds, bim files and fixed cascades

Revision ID: 5c89c3996c0d
Revises: dca29f3a9eeb
Create Date: 2026-03-21 08:45:35.198891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c89c3996c0d'
down_revision: Union[str, Sequence[str], None] = 'dca29f3a9eeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('invite_links_workspace_id_fkey'), 'invite_links', type_='foreignkey')
    op.create_foreign_key(None, 'invite_links', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('memberships_workspace_id_fkey'), 'memberships', type_='foreignkey')
    op.create_foreign_key(None, 'memberships', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('projects_workspace_id_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_workspace_id_fkey'), 'projects', 'workspaces', ['workspace_id'], ['id'])
    op.drop_constraint(None, 'memberships', type_='foreignkey')
    op.create_foreign_key(op.f('memberships_workspace_id_fkey'), 'memberships', 'workspaces', ['workspace_id'], ['id'])
    op.drop_constraint(None, 'invite_links', type_='foreignkey')
    op.create_foreign_key(op.f('invite_links_workspace_id_fkey'), 'invite_links', 'workspaces', ['workspace_id'], ['id'])
    # ### end Alembic commands ###
