"""add project preview file

Revision ID: 5ecfd72ed3f8
Revises: dd6a5379c51a
Create Date: 2026-07-13 16:17:20.683349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ecfd72ed3f8'
down_revision: Union[str, Sequence[str], None] = 'dd6a5379c51a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bims', sa.Column('preview_file_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'bims', ['preview_file_id'])
    op.create_foreign_key(None, 'bims', 'files', ['preview_file_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint(None, 'refresh_tokens', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_tokens', type_='unique')
    op.drop_constraint(None, 'bims', type_='foreignkey')
    op.drop_constraint(None, 'bims', type_='unique')
    op.drop_column('bims', 'preview_file_id')
    # ### end Alembic commands ###
