"""update file models

Revision ID: 66aad46f628c
Revises: b1847854d4b0
Create Date: 2026-04-23 17:54:09.673034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66aad46f628c'
down_revision: Union[str, Sequence[str], None] = 'b1847854d4b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bims', sa.Column('point_cloud_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'bims', ['point_cloud_id'])
    op.create_foreign_key(None, 'bims', 'point_clouds', ['point_cloud_id'], ['id'], ondelete='SET NULL')
    op.add_column('point_clouds', sa.Column('converted_key_prefix', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'point_clouds', ['converted_key_prefix'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'point_clouds', type_='unique')
    op.drop_column('point_clouds', 'converted_key_prefix')
    op.drop_constraint(None, 'bims', type_='foreignkey')
    op.drop_constraint(None, 'bims', type_='unique')
    op.drop_column('bims', 'point_cloud_id')
    # ### end Alembic commands ###
