"""add unique user constraint on Memberships

Revision ID: 6a624678e56a
Revises: 04f7d31193e8
Create Date: 2026-03-12 13:27:29.466933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a624678e56a'
down_revision: Union[str, Sequence[str], None] = '04f7d31193e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_per_workspace', 'memberships', ['user_id', 'workspace_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_per_workspace', 'memberships', type_='unique')
    # ### end Alembic commands ###
