"""add converted point cloud table

Revision ID: 6ba7ac92ebe1
Revises: 66aad46f628c
Create Date: 2026-05-13 10:52:17.057849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ba7ac92ebe1'
down_revision: Union[str, Sequence[str], None] = '66aad46f628c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('point_cloud_converted',
    sa.Column('point_cloud_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['point_cloud_id'], ['point_clouds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_constraint(op.f('point_clouds_converted_key_prefix_key'), 'point_clouds', type_='unique')
    op.drop_column('point_clouds', 'converted_key_prefix')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('point_clouds', sa.Column('converted_key_prefix', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('point_clouds_converted_key_prefix_key'), 'point_clouds', ['converted_key_prefix'], postgresql_nulls_not_distinct=False)
    op.drop_table('point_cloud_converted')
    # ### end Alembic commands ###
