"""remove inviter from InviterLink

Revision ID: 7565e7260f5b
Revises: 1ccfeca2e148
Create Date: 2026-03-12 09:03:13.798862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7565e7260f5b'
down_revision: Union[str, Sequence[str], None] = '1ccfeca2e148'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('invite_links_inviter_id_fkey'), 'invite_links', type_='foreignkey')
    op.drop_column('invite_links', 'inviter_id')
    op.drop_column('workspaces', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('role', postgresql.ENUM('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='roles'), autoincrement=False, nullable=False))
    op.add_column('invite_links', sa.Column('inviter_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('invite_links_inviter_id_fkey'), 'invite_links', 'users', ['inviter_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
