"""actually add task model

Revision ID: 8121119af409
Revises: 02157d6e26bf
Create Date: 2026-06-03 14:53:35.275702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8121119af409'
down_revision: Union[str, Sequence[str], None] = '02157d6e26bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('celery_task_id', sa.String(), nullable=True),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('CHECKING_PROGRESS', 'COMPARING_PLAN_FACT', 'CONVERTING_BIM', 'CONVERTING_POINT_CLOUD', name='task_type', create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'STARTED', 'SUCCEEDED', 'FAILED', 'CANCELED', name='task_status', create_constraint=True), nullable=False),
    sa.Column('meta', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('celery_task_id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###
