"""add point cloud types

Revision ID: 85c74850fbbe
Revises: 10d5e1a82494
Create Date: 2026-05-20 12:42:36.488083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '85c74850fbbe'
down_revision: Union[str, Sequence[str], None] = '10d5e1a82494'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    status_enum = postgresql.ENUM(
        'PLAN', 'SCAN', name='point_cloud_types', create_constraint=True)
    status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('point_clouds', sa.Column(
        'type', status_enum, nullable=False))
    op.alter_column('point_clouds', 'stage_id',
                    existing_type=sa.UUID(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('point_clouds', 'stage_id',
                    existing_type=sa.UUID(),
                    nullable=False)
    op.drop_column('point_clouds', 'type')
    # ### end Alembic commands ###
