"""fix task relationship with reports

Revision ID: 995848684be6
Revises: 8121119af409
Create Date: 2026-06-03 16:29:34.665500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '995848684be6'
down_revision: Union[str, Sequence[str], None] = '8121119af409'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('recording_results_xlsx_report_id_fkey'), 'recording_results', type_='foreignkey')
    op.drop_constraint(op.f('recording_results_pdf_report_id_fkey'), 'recording_results', type_='foreignkey')
    op.create_foreign_key(None, 'recording_results', 'files', ['xlsx_report_id'], ['id'])
    op.create_foreign_key(None, 'recording_results', 'files', ['pdf_report_id'], ['id'])
    op.create_unique_constraint(None, 'tasks', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='unique')
    op.drop_constraint(None, 'recording_results', type_='foreignkey')
    op.drop_constraint(None, 'recording_results', type_='foreignkey')
    op.create_foreign_key(op.f('recording_results_pdf_report_id_fkey'), 'recording_results', 'files', ['pdf_report_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('recording_results_xlsx_report_id_fkey'), 'recording_results', 'files', ['xlsx_report_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
