"""add stage model

Revision ID: a0f7f94e7c81
Revises: bef795f7de4c
Create Date: 2026-03-26 06:41:14.698894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0f7f94e7c81'
down_revision: Union[str, Sequence[str], None] = 'bef795f7de4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stages',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('point_cloud_files', sa.Column('stage_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('point_cloud_files_project_id_fkey'), 'point_cloud_files', type_='foreignkey')
    op.create_foreign_key(None, 'point_cloud_files', 'stages', ['stage_id'], ['id'], ondelete='CASCADE')
    op.drop_column('point_cloud_files', 'project_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('point_cloud_files', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'point_cloud_files', type_='foreignkey')
    op.create_foreign_key(op.f('point_cloud_files_project_id_fkey'), 'point_cloud_files', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_column('point_cloud_files', 'stage_id')
    op.drop_table('stages')
    # ### end Alembic commands ###
