"""add task step model

Revision ID: a44abb190cfb
Revises: dd6a5379c51a
Create Date: 2026-07-03 17:43:20.238542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a44abb190cfb'
down_revision: Union[str, Sequence[str], None] = 'dd6a5379c51a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_steps',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('step_task_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('step_task_id')
    )
    op.create_unique_constraint(None, 'refresh_tokens', ['id'])
    op.add_column('tasks', sa.Column('steps', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('tasks_celery_task_id_key'), 'tasks', type_='unique')
    op.drop_column('tasks', 'celery_task_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('celery_task_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('tasks_celery_task_id_key'), 'tasks', ['celery_task_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('tasks', 'steps')
    op.drop_constraint(None, 'refresh_tokens', type_='unique')
    op.drop_table('task_steps')
    # ### end Alembic commands ###
