"""fix stage model to one point cloud

Revision ID: b02f5e30904e
Revises: 26881c98b938
Create Date: 2026-05-28 15:16:09.901582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b02f5e30904e'
down_revision: Union[str, Sequence[str], None] = '26881c98b938'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recording_results', sa.Column('point_cloud_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'recording_results', ['point_cloud_id'])
    op.create_foreign_key(None, 'recording_results', 'point_clouds', ['point_cloud_id'], ['id'], ondelete='SET NULL')
    op.add_column('stages', sa.Column('point_cloud_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'stages', 'point_clouds', ['point_cloud_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stages', type_='foreignkey')
    op.drop_column('stages', 'point_cloud_id')
    op.drop_constraint(None, 'recording_results', type_='foreignkey')
    op.drop_constraint(None, 'recording_results', type_='unique')
    op.drop_column('recording_results', 'point_cloud_id')
    # ### end Alembic commands ###
