"""init

Revision ID: b3f8030d8922
Revises: 
Create Date: 2026-03-26 19:27:05.135362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3f8030d8922'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bim_files', sa.Column('content_type', sa.String(), nullable=False))
    op.drop_column('bim_files', 'extension')
    op.add_column('point_cloud_files', sa.Column('content_type', sa.String(), nullable=False))
    op.drop_column('point_cloud_files', 'extension')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('point_cloud_files', sa.Column('extension', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('point_cloud_files', 'content_type')
    op.add_column('bim_files', sa.Column('extension', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('bim_files', 'content_type')
    # ### end Alembic commands ###
