"""fix bug with invite link deleting workspaces on cascade

Revision ID: dca29f3a9eeb
Revises: 6a624678e56a
Create Date: 2026-03-12 14:25:44.041475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dca29f3a9eeb'
down_revision: Union[str, Sequence[str], None] = '6a624678e56a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
