"""Update models

Revision ID: e0ba5453962d
Revises: b1d5c33b94b5
Create Date: 2026-02-21 13:24:00.290445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0ba5453962d'
down_revision: Union[str, Sequence[str], None] = 'b1d5c33b94b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('PERSONAL', 'TEAM', name='workspace_types', create_constraint=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('invitations', sa.Column('token_hashed', sa.String(), nullable=False))
    op.add_column('invitations', sa.Column('workspace_id', sa.Integer(), nullable=False))
    op.add_column('invitations', sa.Column('expires_at', sa.DateTime(), nullable=False))
    op.drop_constraint(op.f('invitations_company_id_fkey'), 'invitations', type_='foreignkey')
    op.create_foreign_key(None, 'invitations', 'workspaces', ['workspace_id'], ['id'])
    op.drop_column('invitations', 'token')
    op.drop_column('invitations', 'company_id')
    op.add_column('memberships', sa.Column('workspace_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('memberships_company_id_fkey'), 'memberships', type_='foreignkey')
    op.create_foreign_key(None, 'memberships', 'workspaces', ['workspace_id'], ['id'])
    op.drop_column('memberships', 'company_id')
    op.drop_table('companies')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memberships', sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'memberships', type_='foreignkey')
    op.create_foreign_key(op.f('memberships_company_id_fkey'), 'memberships', 'companies', ['company_id'], ['id'])
    op.drop_column('memberships', 'workspace_id')
    op.add_column('invitations', sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('invitations', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'invitations', type_='foreignkey')
    op.create_foreign_key(op.f('invitations_company_id_fkey'), 'invitations', 'companies', ['company_id'], ['id'])
    op.drop_column('invitations', 'expires_at')
    op.drop_column('invitations', 'workspace_id')
    op.drop_column('invitations', 'token_hashed')
    op.create_table('companies',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('companies_pkey')),
    sa.UniqueConstraint('name', name=op.f('companies_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('workspaces')
    # ### end Alembic commands ###
