"""update task models

Revision ID: e21523a7d21f
Revises: a44abb190cfb
Create Date: 2026-07-06 17:52:33.668684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e21523a7d21f'
down_revision: Union[str, Sequence[str], None] = 'a44abb190cfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'task_steps', ['id'])
    op.alter_column('tasks', 'progress',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('tasks', 'steps',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'steps',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tasks', 'progress',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_constraint(None, 'task_steps', type_='unique')
    # ### end Alembic commands ###
