"""fix point cloud to stage connection

Revision ID: f30fb4fed8db
Revises: b02f5e30904e
Create Date: 2026-05-28 15:20:56.111827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f30fb4fed8db'
down_revision: Union[str, Sequence[str], None] = 'b02f5e30904e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('stages_point_cloud_id_fkey'), 'stages', type_='foreignkey')
    op.drop_column('stages', 'point_cloud_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stages', sa.Column('point_cloud_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('stages_point_cloud_id_fkey'), 'stages', 'point_clouds', ['point_cloud_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
