"""add inviter and remove unique contsr in InviteLink

Revision ID: f8b09436fd17
Revises: 7565e7260f5b
Create Date: 2026-03-12 10:54:53.959877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8b09436fd17'
down_revision: Union[str, Sequence[str], None] = '7565e7260f5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invite_links', sa.Column('inviter_id', sa.Integer(), nullable=False))
    op.add_column('invite_links', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('unique_invite_link_per_role'), 'invite_links', type_='unique')
    op.create_foreign_key(None, 'invite_links', 'users', ['inviter_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invite_links', type_='foreignkey')
    op.create_unique_constraint(op.f('unique_invite_link_per_role'), 'invite_links', ['role', 'workspace_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('invite_links', 'expires_at')
    op.drop_column('invite_links', 'inviter_id')
    # ### end Alembic commands ###
